### ISSUE TITLE
Adding behaviours: ['Timestamp'] crashes the app: Error: The field definition in the "Post" class schema has to be a string, an object or left empty

### ISSUE THREAD

**Issue by banglashi** [jagi/meteor-astronomy-behaviors#1]
Hi @jagi ,

in lib/behaviours/timestamp/timestamp.js the fields createdAt and updatedAt are defined with null, but on the schema.js of jagi:astronomy you just check for isUndefined. Perhaps you should either also check for isNull or just change the fields to undefined. Does that make sense for you?

**Comment by lukejagodzinski** [comment]
Sorry, I haven't updated behaviors module to work with the newest version of the Meteor Astronomy. I'm making fix. It will be ready in an hour.

**Comment by lukejagodzinski** [comment]
Ok, fix for Timestamp published, however making fix for other behaviors will require more time. Hope you are not using them.

**Comment by lukejagodzinski** [comment]
I've updated behaviors and now you can also pass option to behavior and modify the way it behaves. Now, instead adding `jagi:astronomy-behaviors` you have to add particular behavior that you want to use, for example: `meteor add jagi:astronomy-timestamp-behavior` or `meteor add jagi:astronomy-sort-behavior`.

**Comment by banglashi** [comment]
Hi @jagi,

thanks a lot for the quick fix. I like the way you are approaching model, validation and behaviours for meteor.

Just to let you know, I tried to drop-in your package on a current project I am working in, there seems to be some issues when also using meteorhacks:fast-render or copleykj:simple-publish, but I think it's just more related to how this packages work.

Any idea when you will approach "Automatic related object fetching" ?

Thanks and best regards

**Comment by lukejagodzinski** [comment]
No problem.

Right now I have to create video tutorial on how to use Meteor Astronomy and create some examples. After that I will focus on relations definition and related objects fetching. I hope I will start doing it before the end of May. Creating video tutorials needs some time. It's important for me to increase the Meteor Astronomy usage so that I will have more feedback from real life applications. I don't want to create tool for myself but for all developers. Their feedback will be valuable.

When I'will start working on Automatic related objects fetching I will start new issue where I will want to get feedback on how it should look like.

Stay tuned :)
