### ISSUE TITLE
Code style to remark

### ISSUE THREAD

**Issue by dstollie** [jagi/meteor-astronomy-behaviors#3]
In the examples I see
oninitclass
oninitbehaviour

in all the other code I see ur using lowerCamelCase why aren't you using that type of writing everywhere in your code?

**Comment by lukejagodzinski** [comment]
It's because of the events naming standard. For example you have the `window.onclick` not `window.onClick`. The same is true about `window.addEventListener('mousedown')` not `window.addEventListener('mouseDown')`. So I'm not breaking here any rules, just following the standard.

In the last update (0.9.0) I also made few changes to API and for example to create module instead writing `Astronomy.Module` you write `Astronomy.createModule`. The first upper case letter is reserved for global objects and constructors.

In the last update I've also change the way, the events are defined in the behaviors and modules.

I just want to follow w3c standards. In fact Meteor is not doing it in the best way. The best way would be to define events using `on` or `addEventListener` methods. Now we have `Accounts.onCreateUser` and should be for instance `Accounts.on('createuser')` but it's not big deal.

This way we could define multiple events instead only one. But probably it's no the way they wanted it to work.

**Comment by lukejagodzinski** [comment]
Moreover you can use whatever style you want. Internally it makes all event names lowercase. So you can write `addEvent('initclass')` and `addEvent('initClass')`.
